In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(
    'URT2.txt',
    sep=',', header=None, names=['id'])
df

                id
0   Vigun07g160400
1   Vigun02g131200
2   Vigun09g035500
3   Vigun09g261300
4   Vigun03g383400
5   Vigun02g031100
6   Vigun11g192200
7   Vigun07g296800
8   Vigun11g225500
9   Vigun09g152600
10  Vigun11g209400
11  Vigun03g187500
12  Vigun03g211500
13  Vigun08g003900
14  Vigun07g163000
15  Vigun07g160500
16  Vigun11g146100
17  Vigun06g143900
18  Vigun05g298600
19  Vigun09g212500
20  Vigun06g238100
21  Vigun06g088100
22  Vigun04g201800
23  Vigun03g370900
24  Vigun04g166600
25  Vigun06g205400
26  Vigun02g157200
27  Vigun08g186100
28  Vigun05g286100
29  Vigun09g122900
30  Vigun01g003400
31  Vigun05g073500
32  Vigun09g004100
33  Vigun08g205200
34  Vigun03g449000
35  Vigun03g292800
36  Vigun06g113500
37  Vigun11g074100
38  Vigun07g262100
39  Vigun03g404200
40  Vigun07g164200
41  Vigun11g116300
42  Vigun10g060300
43  Vigun04g156600
44  Vigun07g088800
45  Vigun01g223400
46  Vigun06g148200

In [3]:
from intermine.webservice import Service
service = Service("https://phytozome.jgi.doe.gov/phytomine/service")

query = service.new_query("Gene")

query.add_view(
    "name", "primaryIdentifier", "secondaryIdentifier", "length",
    "flankingRegions.length", "flankingRegions.includeGene",
    "flankingRegions.direction", "flankingRegions.primaryIdentifier",
    "flankingRegions.sequence.length", "flankingRegions.sequence.residues"
)

query.add_constraint("flankingRegions.length", "=", "5000", code = "A")
query.add_constraint("flankingRegions.includeGene", "=", "false", code = "B")
query.add_constraint("flankingRegions.direction", "=", "upstream", code = "C")

with open ("URT2 Promoters.txt", "w") as promotores:
    for i in df['id']:
        query.add_constraint("name", "=", i, code = "D")
        for row in query.rows():
            promotores.write(str(row["primaryIdentifier"])+' '+\
                             str(row["flankingRegions.length"])+' '+\
                             str(row["flankingRegions.direction"])+' '+\
                             str(row["flankingRegions.sequence.residues"][3000:])+'\n') #Salvar apenas as ultimas 2000 bases