In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(
    '16UR.txt',
    sep=',', header=None, names=['id'])
df

                id
0   Vigun05g153200
1   Vigun11g060800
2   Vigun09g035500
3   Vigun03g271800
4   Vigun09g182200
5   Vigun04g201700
6   Vigun09g098600
7   Vigun01g124400
8   Vigun08g003900
9   Vigun02g015100
10  Vigun07g150200
11  Vigun09g270200
12  Vigun02g143300
13  Vigun07g244000
14  Vigun09g164900
15  Vigun11g136400
16  Vigun04g003900
17  Vigun09g123200
18  Vigun01g152900
19  Vigun07g116300
20  Vigun07g208400
21  Vigun03g072200
22  Vigun11g206300
23  Vigun10g150200
24  Vigun05g300100
25  Vigun05g005200
26  Vigun06g163900
27  Vigun01g146000
28  Vigun05g063500
29    VigunL033000
..             ...
33  Vigun02g167400
34  Vigun09g152100
35  Vigun01g003400
36  Vigun11g168900
37  Vigun09g071000
38  Vigun05g044600
39  Vigun10g086100
40  Vigun06g143500
41  Vigun09g110600
42  Vigun03g386000
43  Vigun05g040400
44  Vigun11g037300
45  Vigun06g000600
46  Vigun02g077300
47  Vigun09g226800
48  Vigun04g065300
49  Vigun03g388700
50  Vigun07g072000
51  Vigun04g095100
52  Vigun11g074100
53  Vigun03g018400
54  Vigun04g080400
55  Vigun04g152800
56  Vigun07g108400
57  Vigun09g163900
58  Vigun02g114000
59  Vigun01g129400
60  Vigun03g266300
61  Vigun10g136600
62  Vigun05g278600

[63 rows x 1 columns]

In [3]:
from intermine.webservice import Service
service = Service("https://phytozome.jgi.doe.gov/phytomine/service")

query = service.new_query("Gene")

query.add_view(
    "name", "primaryIdentifier", "secondaryIdentifier", "length",
    "flankingRegions.length", "flankingRegions.includeGene",
    "flankingRegions.direction", "flankingRegions.primaryIdentifier",
    "flankingRegions.sequence.length", "flankingRegions.sequence.residues"
)

query.add_constraint("flankingRegions.length", "=", "5000", code = "A")
query.add_constraint("flankingRegions.includeGene", "=", "false", code = "B")
query.add_constraint("flankingRegions.direction", "=", "upstream", code = "C")

with open ("16UR Promoters.txt", "w") as promotores:
    for i in df['id']:
        query.add_constraint("name", "=", i, code = "D")
        for row in query.rows():
            promotores.write(str(row["primaryIdentifier"])+' '+\
                             str(row["flankingRegions.length"])+' '+\
                             str(row["flankingRegions.direction"])+' '+\
                             str(row["flankingRegions.sequence.residues"][4000:])+'\n') #Salvar apenas as ultimas 2000 bases